### PR TITLE
Fixing Alpine Build

### PR DESCRIPTION
**Pull request by allenss-amazon**
The Alpine build of valkey-bundle has been failing since #1360 ("New memory
allocation machinery"). That change reaches the system allocator through
glibc-private symbols, which musl does not export, so `./build.sh` fails to
link on Alpine:

```
/vmsdk/src/memory_allocation_overrides.h:70: undefined reference to `__libc_free'
/vmsdk/src/memory_allocation_overrides.h:62: undefined reference to `__libc_malloc'
collect2: error: ld returned 1 exit status
```

Release images pin search tags and are unaffected, but `unstable-alpine` builds
`main` at image build time, so the nightly has been red. Fixing the link error
uncovered three more musl-only failures underneath it, and testing on Alpine
surfaced a fourth, older one (commit 5).

**No build-environment changes are needed** -- no new packages, and
`vmsdk/src/CMakeLists.txt` is untouched. gcompat was evaluated and rejected: it
would have added a runtime dependency for three wrapper functions.

## The commits

1. **`match libc's exception specification on musl`** -- glibc declares
   `malloc` and friends `__THROW` (noexcept in C++); musl declares them with no
   exception specification. clang rejects the mismatch outright, so the module
   does not compile with clang on musl. gcc only accepts it, which is why the
   build got as far as failing on something else. The specification is now
   conditional on `__GLIBC__`.

2. **`fix two ShardedAtomic lifetime bugs found on musl`** -- both are
   use-after-destroy on the accounting path. A thread's `ThreadLocalNode` is
   destroyed before `thread_local`s constructed earlier, so a destructor that
   frees memory reports through a node whose values array is already gone
   (SIGSEGV in a worker thread at `SHUTDOWN`). And the `CounterRegistry` could
   be destroyed before the main thread's node, whose destructor then walks a
   freed vector (SIGSEGV in `exit()` after every test in `commands_test`
   passed). glibc hides both: it leaves freed memory mapped, and it runs
   `thread_local` destructors before static ones.

3. **`allocate the counters' own memory from ValkeyModule_Alloc`** -- removes
   the `__libc_malloc`/`__libc_free` dependency. `ValkeyModule_Alloc` is the
   same heap without the reporting, so it breaks the same re-entrancy cycle and
   exists on every platform; the memory also becomes visible to Valkey's own
   `used_memory`. Two supporting changes make it safe: the registry's
   containers get inline capacity, so static initialization allocates nothing
   (measured: 3 allocations before `main`, now 0), and the unit tests install a
   plain malloc-backed implementation before `main` rather than routing through
   the per-test mock, which is deleted in `TearDown` while this memory lives for
   the whole process.

4. **`resolve realpath without glibc's __realpath_chk`** -- the last
   glibc-private name. Our `realpath` cannot call libc's (that name binds to our
   own definition and recurses), so it used glibc's fortified entry point. It
   now lets the kernel resolve: `open(O_PATH)` plus `readlink("/proc/self/fd/N")`,
   which allocates nothing and behaves identically on both libcs. `/proc` is
   not a new dependency -- `thread_group_cpu_monitor.cc` already walks
   `/proc/self/task`. Both forms are supported: with `nullptr`, the path is
   resolved into a stack buffer and returned via `strdup` -- inside the module
   that is the module's own `strdup`, allocating from `ValkeyModule_Alloc`, so
   the caller's `free()` is the module's too, as with `getcwd(nullptr, 0)`.
   The resolver lives in `vmsdk::RealPath`, which the module's `realpath`
   delegates to, so the unit tests exercise the real code
   (`memory_allocation_c_api.cc` itself cannot be linked into a test binary).
   Also teaches `ci/check_module_allocators.sh` about musl:
   `_init`/`_fini` are exported by every DSO there, and `libc.musl-*.so.1` is
   the architecture-specific libc.

5. **`have each ThreadPool worker record its own thread id`** -- predates
   #1360, but crashed the server under `INFO` about 1 run in 4 on Alpine, and
   `core_test` about 2 in 15. A worker built its `ThreadMonitor` from the
   `thread_id` that `pthread_create` fills in for the parent, and POSIX does
   not order that store before the new thread runs: musl makes it after
   `__clone`, so the worker read 0 in 106 of 20,000 creations (glibc: none).
   `INFO` then passed that 0 to `pthread_getcpuclockid`, which dereferences it.
   The worker now sets `thread_id` from `pthread_self()` and names itself; the
   parent sets the name before `pthread_create` and no longer reads the id
   until `IsJoinable()` has synchronized with the worker. `pthread_create`'s
   result, previously ignored, is now CHECKed.

## Verification

Alpine build image is `valkey/valkey:unstable-alpine` plus the bundle's package
list, gcc 15.2 / clang 21.1, with **gcompat not installed**.

- glibc: `./build.sh --run-tests` clean, 13/13 test binaries pass.
- musl: `./build.sh --run-tests` clean, 13/13 pass.
- `core_test`, which was flaky on musl before commit 5: 0 failures in 200 runs
  on each libc. `INFO` under load on Alpine: 0 crashes in 10 server runs.
- TSan (`./build.sh --tsan --run-tests`): 13/13 pass, no data-race reports.
- Module loads into `valkey-server` on Alpine; `FT.CREATE`, `HSET`, text/tag/
  numeric `FT.SEARCH`, `FT.INFO` and `INFO modules` all work, and `SHUTDOWN` is
  clean across repeated runs.
- `libsearch.so` has no glibc-private imports; `NEEDED` is `libssl`,
  `libcrypto`, `libgcc_s`, `libc.musl-x86_64`.
- Reported memory is unchanged (`search_used_memory_bytes` within noise of the
  previous implementation on the same workload).
- `realpath` was called directly against the loaded module on musl:
  `/etc/localtime` resolves to its zoneinfo target (ICU's `uprv_tzname` makes
  exactly this call, and reaches our definition on musl because there is no
  fortified variant), symlink chains and `..` resolve, a missing path returns
  `nullptr`, and the allocating form returns heap strings. The built module
  calls its own local `strdup` there, not `strdup@plt`.
- New `utils_test` cases cover both `realpath` forms on both libcs: `"."`
  resolves to an absolute path equal to `getcwd`, and a missing path returns
  `nullptr` with `ENOENT`.
- Each commit compiles independently.

## Follow-up

valkey-search has no Alpine/musl CI job, which is why all of these reached
`main` unnoticed. Adding one would stop the next release tag shipping the
same way.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: vmsdk/src/sharded_atomic.h [hunk 1]
```diff
@@ -40,6 +42,9 @@ class ShardedAtomic {
 
   // THE HOT PATH (Write)
   inline void Add(T n) {
+    if (ABSL_PREDICT_FALSE(node_destroyed_)) {
+      return;
+    }
```
[the remark this answers is not in the document]
Comment (allenss-amazon) [reply vmsdk/src/sharded_atomic.h:47]: pre-existing issue relative to this PR.

File: vmsdk/src/memory_allocation_c_api.cc [hunk 2]
```diff
@@ -172,32 +179,61 @@ char* strdup(const char* s) noexcept {
...
+//
+// The form that takes nullptr is the one with no safe answer: it is defined to
+// return a buffer libc malloc'd, which free() above would later hand to
+// ValkeyModule_Free. Nothing in the module is expected to ask for it --
+// std::filesystem::canonical would, and libstdc++ links it in, but no code
+// here calls it -- so it fails loudly rather than silently allocating memory
+// this allocator cannot account for.
+char* realpath(const char* path, char* resolved_path) VMSDK_LIBC_NOEXCEPT {
+  CHECK(resolved_path != nullptr)
+      << "This function violates memory allocation assumptions";
```
[the remark this answers is not in the document]
Comment (allenss-amazon) [reply vmsdk/src/memory_allocation_c_api.cc]: One of a zillion places we'll crash if malloc fails.

**Review by Frank-Gu-81 — APPROVED** [review]
Looks good to me. the allocator/lifetime, `realpath`, and thread pool changes makes sense to me conceptually.
